### ISSUE TITLE
Wrong IP reported in case of custom IP provided

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/tlsx#112]
### tlsx version:
`main|master` and `dev`

### Current Behavior:
TLSX as a library reports wrong dialed ip (fastdialer lookup is performed on the domain name and will report always the first dialed ip)

### Expected Behavior:
Custom ip should be used if provided at the following locations:
```
https://github.com/projectdiscovery/tlsx/blob/3d5172c6c493efcab4efb836e374a2b5d432e9fc/pkg/tlsx/tls/tls.go#L120
https://github.com/projectdiscovery/tlsx/blob/3d5172c6c493efcab4efb836e374a2b5d432e9fc/pkg/tlsx/ztls/ztls.go#L135
https://github.com/projectdiscovery/tlsx/blob/3d5172c6c493efcab4efb836e374a2b5d432e9fc/pkg/tlsx/openssl/openssl.go#L95
```

### How to reproduce
Using `issue-2141-scan-all-ips` branch in nuclei
```console
$ echo https://hackerone.com | go run . -id tls-version -sa -iv 4 -json -rl 1 -c 1 -bs 1 -v
...
[VER] Sent SSL request to hackerone.com:443
{"template":"\\ssl\\tls-version.yaml","template-url":"https://github.com/projectdiscovery/nuclei-templates/blob/master/\\ssl\\tls-version.yaml","template-id":"tls-version","info":{"name":"TLS Version","author":["pdteam"],"tags":["ssl"],"reference":null,"severity":"info"},"type":"ssl","host":"hackerone.com","matched-at":"hackerone.com","extracted-results":["tls13"],"ip":"104.16.100.52","timestamp":"2022-11-04T21:30:04.673107+01:00","matcher-status":true,"matched-line":null}
[VER] Sent SSL request to hackerone.com:443
{"template":"\\ssl\\tls-version.yaml","template-url":"https://github.com/projectdiscovery/nuclei-templates/blob/master/\\ssl\\tls-version.yaml","template-id":"tls-version","info":{"name":"TLS Version","author":["pdteam"],"tags":["ssl"],"reference":null,"severity":"info"},"type":"ssl","host":"hackerone.com","matched-at":"hackerone.com","extracted-results":["tls13"],"ip":"104.16.100.52","timestamp":"2022-11-04T21:30:04.7559573+01:00","matcher-status":true,"matched-line":null}
```

**Comment by tarunKoyalwar** [comment]
@Mzack9999 

It looks like there is no issue with tlsx instead the bug lies within nuclei implementation of `ScanAllIps` .

Coming to `tlsx` the final call for `ScanAllIps` is done at 

https://github.com/projectdiscovery/tlsx/blob/2d9ef526b4ff9678f72d62189305a9a21d1c4269/pkg/tlsx/tls/tls.go#L97-L104

Here if `ScanAllIps` option is true . function uses `ip address` instead of hostname  like `hackerone.com`  to connect .

this address is used to dial and is  will be returned as `resolvedIp` in furthur steps .

**Comment by tarunKoyalwar** [comment]
## In Nuclei 

Above function is triggered in nuclei at 

https://github.com/projectdiscovery/nuclei/blob/05d607642a11449262fba8d079025dc5325dec8d/v2/pkg/protocols/ssl/ssl.go#L164-L167

i.e 
```go
response, err := request.tlsx.Connect(host, host, port)
```

instead of passing `ip` if `scanallIps` is enabled nuclei always passes hostname to tlsx . when connecting using hostname only one of the ip is selected .
