### ISSUE TITLE
TLS Connection errors investigation

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/tlsx#31]
- [x] **remote error: internal error**

```console
echo 209.17.116.160 | tlsx -silent -v

[INF] Processing input 209.17.116.160:443
[WRN] Could not connect input 209.17.116.160:443: could not connect to host: could not do handshake: remote error: tls: internal error
```

https://www.shodan.io/host/209.17.116.160#443

- [x] **could not do handshake: EOF**

```console
echo 1.6.23.18 | tlsx -silent -v
[INF] Processing input 1.6.23.18:443
[WRN] Could not connect input 1.6.23.18:443: could not connect to host: could not do handshake: EOF
```

- [x] **remote error: tls: handshake**

```console
echo 1.0.0.102 | tlsx -silent -v
[INF] Processing input 1.0.0.102:443
[WRN] Could not connect input 1.0.0.102:443: could not connect to host: could not do handshake: remote error: tls: handshake failure
```

- [x] **oversized record received with length XXXX**

```console
echo 1.2.220.218 | tlsx -silent -v -sm ztls
[INF] Processing input 1.2.220.218:443
[WRN] Could not connect input 1.2.220.218:443: could not connect to host: could not do tls handshake: tls: oversized record received with length 20527
```

- [x] **tls: bad certificate**

```console
echo 24.196.75.118 | tlsx -silent -v
[INF] Processing input 24.196.75.118:443
[WRN] Could not connect input 24.196.75.118:443: could not connect to host: could not do handshake: remote error: tls: bad certificate
```

- [x] **tls: unrecognized name**

```console
echo 4.4.89.33 | tlsx -silent -v
[INF] Processing input 4.4.89.33:443
[WRN] Could not connect input 4.4.89.33:443: could not connect to host: could not do handshake: remote error: tls: unrecognized name
```

- [x] **remote error: alert(112)**

```console
echo 4.4.89.33 | tlsx -silent -sm auto -v
[INF] Processing input 4.4.89.33:443
[WRN] Could not connect input 4.4.89.33:443: could not connect to host: could not do tls handshake: remote error: alert(112)
```

**Comment by Mzack9999** [comment]
- [ ] **remote error: internal error** fails with openssl and curl => expected
- [ ] **could not do handshake: EOF** fails with openssl and curl => expected
- [ ] **remote error: tls: handshake** fails with openssl and curl => expected
- [ ] **oversized record received with length XXXX** => not reproducible because of time out
- [ ] **tls: bad certificate** openssl parse the certificate but fails to connect, curl and ncat fails => expected
- [ ] **tls: unrecognized name** => not reproducible because of time out
- [ ] **remote error: alert(112)** => not reproducible because of time out

In order to increase success ratio we could consider adding a third mechanism that uses openssl if available
